# Generated by Django 4.2.11 on 2024-05-08 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stundent',
            new_name='Student',
        ),
    ]
